variables:
  GIT_SUBMODULE_STRATEGY: normal
  BUNDLE: "roger-dev.flatpak"

stages:
  - build
  - flatpak

fedora-x86_64:
  image: registry.gitlab.com/tabos/rogerrouter/linux:v2
  stage: build
  script:
    - meson _build
    - ninja -C _build
    - ninja -C _build test
  artifacts:
    paths:
      - "_build/meson-logs"
    when: on_failure

windows:
  image: registry.gitlab.com/tabos/rogerrouter/mxe:v1
  stage: build
  script:
    - meson _build --cross-file=platform/windows/mingw-cross.txt --libdir=lib --prefix=${CI_PROJECT_DIR}/installed/
    - ninja -C _build
    - ninja -C _build install
    - makensis -dMXE_SYSROOT=/opt/mxe/usr/i686-w64-mingw32.shared.posix/ -dPREFIX=${CI_PROJECT_DIR}/installed/ _build/platform/windows/roger.nsi
  artifacts:
    paths:
      - "_build/meson-logs"
      - "_build/platform/windows/*.exe"

flatpak:
  image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
  stage: flatpak
  variables:
    MANIFEST_PATH: "platform/linux/org.tabos.roger.json"
    MESON_ARGS: ""
    FLATPAK_MODULE: "roger"
    RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
    DBUS_ID: "org.tabos.roger"

  script:
    - flatpak-builder --stop-at=${FLATPAK_MODULE} app ${MANIFEST_PATH}
    # Make sure to keep this in sync with the Flatpak manifest, all arguments
    # are passed except the config-args because we build it ourselves
    - flatpak build app meson --prefix=/app ${MESON_ARGS} _build
    - flatpak build app ninja -C _build install
    - flatpak-builder --finish-only --repo=repo app ${MANIFEST_PATH}
    # Generate a Flatpak bundle
    - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} ${DBUS_ID}
    # Run automatic tests inside the Flatpak env
    - flatpak build app ninja -C _build test
  artifacts:
    when: 'always'
    paths:
      - "${BUNDLE}"
      - '_build/meson-logs/meson-log.txt'
      - '_build/meson-logs/testlog.txt'
      - 'repo'
    expire_in: 2 days
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - '.flatpak-builder/downloads'
      - '.flatpak-builder/git'
