variables:
  GIT_SUBMODULE_STRATEGY: normal
  BUNDLE: "roger-dev.flatpak"

stages:
  - check
  - build

check-code-style:
  stage: check
  image: alpine:latest
  interruptible: true
  before_script:
    - apk update && apk add uncrustify bash python3
  script:
    - bash data/check-code-style

scan-build:
  image: registry.gitlab.com/tabos/rogerrouter/linux:v5
  stage: check
  script:
    - meson _build
    - ninja -C _build scan-build
    - bash -c 'if [[ -n "$(ls -A _build/meson-logs/scanbuild/)" ]]; then echo "Scan build log found, assuming defects exist"; exit 1; fi'
  allow_failure: true
  artifacts:
    when: on_failure
    paths:
      - _build/meson-logs/scanbuild

fedora-x86_64:
  image: registry.gitlab.com/tabos/rogerrouter/linux:v5
  stage: build
  script:
    - CC=clang meson _build
    - ninja -C _build
    - ninja -C _build test
  artifacts:
    paths:
      - "_build/meson-logs"
    when: on_failure
