variables:
  GIT_SUBMODULE_STRATEGY: normal
  BUNDLE: "roger-dev.flatpak"

stages:
  - build
  - flatpak
  - deploy

fedora-x86_64:
  image: registry.gitlab.com/tabos/rogerrouter/master:v1
  stage: build
  script:
    - meson _build
    - ninja -C _build
    - ninja -C _build test
  artifacts:
    paths:
      - "_build/meson-logs"
    when: on_failure

flatpak:
  image: flatpak/flatpak-builder:gnome-3-28
  stage: flatpak
  variables:
    MANIFEST_PATH: "platform/linux/org.tabos.roger.flatpak.json"
    MESON_ARGS: ""
    FLATPAK_MODULE: "roger"
    RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
    DBUS_ID: "org.tabos.roger"

  script:
    - flatpak-builder --stop-at=${FLATPAK_MODULE} app ${MANIFEST_PATH}
    # Make sure to keep this in sync with the Flatpak manifest, all arguments
    # are passed except the config-args because we build it ourselves
    - flatpak build app meson --prefix=/app ${MESON_ARGS} _build
    - flatpak build app ninja -C _build install
    - flatpak-builder --finish-only --repo=repo app ${MANIFEST_PATH}
    # Generate a Flatpak bundle
    - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} ${DBUS_ID}
    # Run automatic tests inside the Flatpak env
    - flatpak build app ninja -C _build test
  artifacts:
    when: 'always'
    paths:
      - "${BUNDLE}"
      - '_build/meson-logs/meson-log.txt'
      - '_build/meson-logs/testlog.txt'
      - 'repo'
    expire_in: 2 days
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - '.flatpak-builder/downloads'
      - '.flatpak-builder/git'

repo_deploy:
  image: alpine:3.6
  stage: deploy
  before_script:
    - apk update && apk add openssh-client bash rsync
  script:
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - rsync -avz -e 'ssh' repo "$SSH_USER"@"$SSH_HOST":"$SSH_PATH"
